### ISSUE TITLE
Occasionally, NPCs get stuck on interactive objects.

### ISSUE THREAD

**Issue by songjinxi** [faxcorp/CleverObjectsDemoProject#1]
![image](https://github.com/user-attachments/assets/6d693ff6-fc1a-4339-86f9-6197555bde33)
Occasionally, NPCs get stuck on interactive objects.

**Comment by faxlab** [comment]
Hi. Thanks for making an issue. Its a hard to reproduce problem but I did reproduce and hopefully fixed it. I think the issue was in the BP_CO_Base where it added itself to the overlapping actors array at a wrong time

https://github.com/faxcorp/CleverObjectsDemoProject/commits/fd18f556963076a6a757e80fd4b0c99650a7b0a2/Content/CleverObjectsDemo/CleverObjects/BP_CO_Base.uasset

https://github.com/user-attachments/assets/7a373dc9-9edd-4199-8627-34c275d88faa
